services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      SuperAdmin__Email: ${SUPER_ADMIN_EMAIL}
      SuperAdmin__Password: ${SUPER_ADMIN_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5

  webapi:
    build: ./Northeast
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=${DATABASE_NAME};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"

  frontend:
    build: ./WT4Q
    restart: always
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://server.wt4q.com
      NEXT_PUBLIC_SITE_URL: https://www.wt4q.com
    depends_on:
      - webapi
    ports:
      - "3000:3000"

volumes:
  postgres_data:
